import js from '@eslint/js';
import tseslint from 'typescript-eslint';

// Project ESLint config, generated by CEF and extended for this app.
export default tseslint.config(
  {
    ignores: [
      'dist/**',
      '.next/**',
      'build/**',
      'node_modules/**',
      // Written by `next build`; its triple-slash references are Next's own.
      'next-env.d.ts',
      // Emitted by scripts/prepare-assets.ts.
      'lib/generated/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Build scripts run under `node --experimental-strip-types`, outside the
    // Next.js module graph, so they legitimately import with a .ts extension.
    files: ['scripts/**/*.ts'],
    rules: { '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }] },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    },
  },
);
